channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - folium
  - altair
  - notebook
  - vega
  - nbserverproxy
  - param
  - pyviz_comms
  - datashader
  - holoviews
  - geoviews
  - hvplot
  - bokeh
  - panel
  - tornado<6
  - pandas
  - numpy
  - osmnx
  - shapely
  - geopy
  - nbserverproxy
  - pip:
      - carto
      - pyrestcli
